### ISSUE TITLE
Problem after patching blitz

### ISSUE THREAD

**Issue by xS4yk0x** [lulzsun/blitz-app-adblock#58] opened 2021-07-25 11:19 UTC
Blitz version 1.15.14
After using last release of blitz-app-adblock, blitz just starts first window then terminates. If I reinstalled blitz again, it works fine. I guess they made something to detect modified codes or something, so can you fix this in your next release.
Thanks for your efforts at all

**Comment by Sarm1X** [comment] 2021-07-29 16:08
Duplicate of #56

**Closed** 2021-07-29 20:59 UTC
