### ISSUE TITLE
Blitz crashing

### ISSUE THREAD

**Issue by Sarm1X** [lulzsun/blitz-app-adblock#57] opened 2021-07-10 15:59 UTC
Hey there fella, first thank you for your work!!
Fortunately it does not work in my end, after applying the patch blitz is refusing to start up, I see the initial loading logo then it crashes, any ideas?

**Comment by andranoxi** [comment] 2021-07-11 16:14
dupe of #56

**Closed** 2021-07-29 20:59 UTC
