### ISSUE TITLE
Blitz Crashes after Install

### ISSUE THREAD

**Issue by tazzrawr** [lulzsun/blitz-app-adblock#61] opened 2021-09-21 16:55 UTC
I used the Adblock tool however when I open up Blitz again the splash appears and then crashes and closes. 

It says "Starting Blitz" .... "Connecting".... then crashes.

**Comment by abusiv0** [comment] 2021-09-22 23:20
same

**Comment by lulzsun** [comment] 2021-09-23 00:14
Duplicate of #56, it has been known for quite some time now. Closing this issue.

**Closed by lulzsun** 2021-09-23 00:14 UTC
